version: "3.8"

networks:
  traefik-network:
    external: true

services:
  frontend:
    container_name: movers-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "1234:1234"
    depends_on:
      - backend
    environment:
      - NODE_ENV=production # Set environment to production
      - REACT_APP_API_URL=http://backend:8000/api/v1
    networks:
      - traefik-network

  backend:
    container_name: movers-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - ENVIRONMENT=production # Set your environment variables here if necessary
      - DEBUG=true
      - API_VERSION=1
      - FRONTEND_URL=http://frontend:1234
    networks:
      - traefik-network
