version: "3.8"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "1234:1234"
    depends_on:
      - backend
    environment:
      - NODE_ENV=production # Set environment to production

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - ENVIRONMENT=production # Set your environment variables here if necessary
